-- MySQL Script generated by MySQL Workbench
-- Tue Jun 18 22:21:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(40) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`penyedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`penyedia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(45) NOT NULL,
  `alamat` VARCHAR(45) NOT NULL,
  `deskripsi` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`layanan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`layanan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(100) NOT NULL,
  `deskripsi` TEXT NOT NULL,
  `harga` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diskon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diskon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kode_diskon` VARCHAR(20) NOT NULL,
  `deskripsi` TEXT NOT NULL,
  `persentase_diskon` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `kode_diskon_UNIQUE` (`kode_diskon` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pelanggan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pelanggan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(45) NOT NULL,
  `alamat` VARCHAR(45) NOT NULL,
  `no_tlp` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `diskon_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pelanggan_user_idx` (`user_id` ASC) ,
  INDEX `fk_pelanggan_diskon1_idx` (`diskon_id` ASC) ,
  CONSTRAINT `fk_pelanggan_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pelanggan_diskon1`
    FOREIGN KEY (`diskon_id`)
    REFERENCES `mydb`.`diskon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pemesanan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pemesanan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `waktu_pemesanan` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `harga_akhir` DECIMAL(10,2) NOT NULL,
  `layanan_id` INT NOT NULL,
  `pelanggan_id` INT NOT NULL,
  `penyedia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pemesanan_layanan1_idx` (`layanan_id` ASC) ,
  INDEX `fk_pemesanan_pelanggan1_idx` (`pelanggan_id` ASC) ,
  INDEX `fk_pemesanan_penyedia1_idx` (`penyedia_id` ASC) ,
  CONSTRAINT `fk_pemesanan_layanan1`
    FOREIGN KEY (`layanan_id`)
    REFERENCES `mydb`.`layanan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pemesanan_pelanggan1`
    FOREIGN KEY (`pelanggan_id`)
    REFERENCES `mydb`.`pelanggan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pemesanan_penyedia1`
    FOREIGN KEY (`penyedia_id`)
    REFERENCES `mydb`.`penyedia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
